/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doomaykacheckstylecritic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;

class AppTest {
    @Test
    void appHasARightMessageGenerator() {
        String result = "";
        String rightResult = "\\\\Doomayka CheckStyle critic//\r\n"
                             + "Lines prepared: 2500\r\n"
                             + "By expression: 10-((1*250+0*0+0*0+0*0)/2500)*10\r\n" 
                             + "Result: 9.0\r\n";

        // Stream for printing in buffer
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;

        System.setOut(ps);

        float rating = (float) 9.0;
        long linesCount = 2500;
        int errorMultiplier = 1;
        int warningMultiplier = 0;
        int refactorMultiplier = 0;
        int conventionMultiplier = 0;
        int errorsCounter = 250;
        int warningsCounter = 0;
        int refactorsCounter = 0;
        int conventionsCounter = 0;
        String[] messages = { 
                            "\\\\Doomayka CheckStyle critic//", 
                            "Lines prepared: %lc",
                            "By expression: 10-((%emp*%ect+%wmp*%wct+%rmp*%rct+%cmp*%cct)/%lc)*10", 
                            "Result: %r" 
                            };

        MessageGenerator msgGenerator = new MessageGenerator(rating, 2500, 1, 0, 0, 0, 250, 0, 0, 0, null);

        msgGenerator.printMessages();
        result = baos.toString();

        assertEquals(rightResult, result);

        System.setOut(old);
    }
}
