/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doomaykacheckstylecritic;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
    	//file options
    	//path
    	//xml name
    	
    	//parse options
    	//errorMessages
    	//warningMessages
    	//refactorMessages
    	//conventionMessages
    	//multipliers(error,warning,refactor,convention)
    	
    	//message options
    	
        CheckStyleParser csp = new CheckStyleParser();
        csp.readXML();
        CheckStyleModel model = csp.getXmlUnparsed();
        CodeCounter counter = new CodeCounter(model,new int[]{1,1,1,1});
        float rating = 0;
        rating = counter.calculate();
        MessageGenerator mGenerator = new MessageGenerator(rating, counter.getLinesPrepared(), counter.getMultipliers(), counter.getCounter());
        mGenerator.printMessages();
    }
}
